pipeline {
  environment {
    registry = "arun92/phphello"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/ankitsnlq/buildproject.git'
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
    stage('DeployToProduction') {
            steps {
                input 'Deploy to Production?'
                milestone(1)
                retry(3) {
                    sh 'chmod +x updatekube.sh'
                    sh 'sed -i -e "s/BUILD_NUMBER/${BUILD_NUMBER}/g" deployphp.yaml'
                    sh './updatekube.sh'
                }
            }
        }
  }
}
